server:
  port: 30001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: ${test}
      secret-key: ${test}
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: naisimall
      sms:
        accessKeyId: ${test}
        accessKeySecret: ${test}
        signName: 欧巴学院在线教育网站
        templateCode: SMS_185246556

  application:
    name: naisimall-third-party
